Full project setup
esatisfaction/esat-prestashop pull request #5
Opened 2018-07-31 10:25 UTC by nickmourman

2018-07-31 11:28 UTC, esat-platforms requested changes
I have some requests and some questions.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        $this->id_shop = Configuration::get('ESATISFACTION_SITE_ID');
We don't have site_id any more. We should remove it.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        $this->displayName = $this->l('e-satisfaction tracking module');
Let's set the name to `E-satisfaction Module`

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        ) ENGINE = MYISAM');
We should define `id_order` or `item_id` as Primary Key here.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +    public function uninstall()
Do we need `uninstall()` on this Module? If yes, I think that the body can be simplified to
```php
return !!parent::uninstall();
```
or
```php
return (bool)parent::uninstall();
```

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +                'ESATISFACTION_CHKOUTID',
I would suggest to set these values to something more readable like `ESATISFACTION_QUESTIONNAIRE_CHECKOUT_ID`, unless there is a character limitation. In the latter case, can we change it to `ESAT_Q_CHECKOUT_ID` ??

Let's apply the same logic for all variables in this context.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +
We should eliminate the blank lines between the doc-block and the function.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +    * @return boolean
Although the doc-block says that it returns `boolean`, the function either returns `void` or no return at all.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        $helper->generateForm($fields_form);
Isn't line 502 unreachable code?

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        if ($extra_options) {
We can set `$extra_options` to have a default value of `array()` and skip this `if` here.

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +     * @return mixed
Perhaps we should remove this `@return` from here?

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +     * @return mixed
Perhaps we should remove this `@return` from here?

2018-07-31 11:28 UTC, esat-platforms commented on esatisfaction.php
> +        `id_order` INT( 11 ) NOT NULL,
Does this have to be `id_order` instead of `order_id`? Is it referenced to a platform's field?

2018-07-31 11:28 UTC, esat-platforms commented on views/css/index.php
> +header('Location: ../');
Is this a standard command? Perhaps we should change it to `header('Location: ../../../');`?

2018-07-31 11:28 UTC, esat-platforms commented on views/img/index.php
> +header('Location: ../');
Same comment here about Location path.

2018-07-31 11:28 UTC, esat-platforms commented on views/index.php
> +header('Location: ../');
Same comment here about Location path.

2018-07-31 11:28 UTC, esat-platforms commented on views/js/index.php
> +header('Location: ../');
Same comment here about Location path.

2018-08-01 08:12 UTC, esat-platforms commented on esatisfaction.php
> +            'appid' => Configuration::get('ESATISFACTION_APP_ID'),
Would it make sense to set this parameter's name to `app_id` to keep consistency?

2018-08-01 08:30 UTC, esat-platforms commented
Let's fix all the style and change all greek comments to english and see how ti goes. Thanks!

2018-08-30 12:16 UTC, nickmourman commented on views/css/index.php
> +header('Location: ../');
It's a standard file for Prestashop

2018-08-30 12:16 UTC, nickmourman commented on views/img/index.php
> +header('Location: ../');
Same as above

2018-08-30 12:16 UTC, nickmourman commented on views/index.php
> +header('Location: ../');
Same as above

2018-08-30 12:17 UTC, nickmourman commented on views/js/index.php
> +header('Location: ../');
Same as above

2018-08-30 12:31 UTC, nickmourman commented on esatisfaction.php
> +            'appid' => Configuration::get('ESATISFACTION_APP_ID'),
OK

2018-08-30 14:09 UTC, nickmourman commented
A blank line between licence comments and code is required for Prestashop Marketplace

2018-08-30 14:13 UTC, ioannis-papikas commented
Let me update the style rules and check again! Thanks @nickmourman !

2018-08-30 14:22 UTC, merged